### ISSUE TITLE
Unclear local development workflow 

### ISSUE THREAD

**Issue by ccrueb** [DCtheTall/node-video-chat#19]
This is an incredible project. I have been rolling my own version of this from scratch the past couple days, and stumbled upon this. I am thinking about scrapping what I have so far, and building on top of your work. I started working through the code, and it is not clear what sort of workflow you used to develop this locally. In `package.json` `yarn start` makes the assumption that webpack has already run and built the project. Did you start webpack from the command line? Did you have any sort of watchers set up/automatic rebuilds? Did you deploy to test all changes?

Apologies if I am missing something obvious.

**Comment by DCtheTall** [comment]
Thanks for the kind words about the project, and glad it's inspiring you to build your own!

Apologies for my complete lack of build documentation. I used NPM for this project and am actually not familiar with Yarn, but I think your suggestion about running Webpack is correct. I usually run webpack with the following flags: `--progress --colors --watch` and of course `--mode`.

Then I just have [nodemon](https://www.npmjs.com/package/nodemon) installed globally and ran that to watch for changes in the JS binary when it rebuilds.

As far as automated testing goes, since this project is just meant for personal use and was never intended to be used for any actual customer-facing production environments, I skipped doing tests 😛 

I never get around to them because I wholeheartedly want to refactor this into TypeScript and perhaps try out a different state management pattern (some day...)

Let me know if running Webpack resolves your issue, if not feel free to post questions here or another issue.
