### ISSUE TITLE
Question regarding GraphQL and WebRTC

### ISSUE THREAD

**Issue by zefexdeveloper** [DCtheTall/node-video-chat#22]
GraphQL has support for subscriptions that uses WebSocket behind the scenes, why is it needed to use Socket.io and not use the GraphQL subscription for things such as signaling? Is there a reason or it was just preference?

The other question I have is regarding the usage of Redux, as you are using Apollo that handles the state for you, why Redux?

Thank you very much

**Comment by DCtheTall** [comment]
Happy to answer your questions! There are a few reasons I chose to use Socket.io and Redux.

At the time I wrote the app (which is now 2 years ago), Apollo did not have built-in local state management (it was added in 2.5.x and this project used 2.2.5). Back then, you could add local state management with a library called apollo-link-state (which is now deprecated). I was not satisfied at the time with how Apollo handled local state and was familiar with Redux.

I used Socket.io for a few reasons actually. The first being that it was, in my opinion, better to separate concerns for the video calling portion of the app from the rest of the app's features. I wanted a separate signaling server from the GraphQL server which really just handles reads/writes to a SQL database. The second is that (at least at the time) Socket.io has much better integration with Redis, which made determining things like whether a user is online easier. It also lets you have multiple instances of the signaling nodes up without needing to query all of the nodes to determine if a user is connected. I preferred to not reinvent the wheel in order to get those features working, since at the time Apollo subscriptions didn't sufficiently meet my needs.

**Comment by zefexdeveloper** [comment]
@DCtheTall I'm planning on implementing it but I'm not sure about separating all of that as most of those libraries allows you to perfectly do things such as local state management and redis support for Redis, RabbitMQ, Kafka, etc.
If you had to update the app nowadays with all the updates those libraries has, what would you change?

**Comment by DCtheTall** [comment]
Here are a few things I might do differently a second time around:

1. Use TypeScript where possible, I won't go into why TS should be used over JS since lots of people can articulate it better than me.

1. I might use RxJS for state management. I think it's event based model makes more sense for what this app is trying to do. GraphQL was a nice tool to learn with this project, but to be honest I don't think it's necessary.

1. Overhaul the entire video call model. There are different designs that more easily allow you to do video calls with more than 1 other person. Also I would like to have the IM just use WebRTC instead of GraphQL subscriptions. I probably want to add some other things, I have been meaning to read the WebRTC spec to get a better idea of what the API can do.

1. Possibly use Angular instead of React? The Googler in me wants to give it another chance, especially now that I actually understand RxJS. 

1. Possibly use a different backend instead of Node.js, most likely Go if it can be done. Though then the project name would have to change 😆

**Comment by zefexdeveloper** [comment]
@DCtheTall I laughed at the "The Googler in me" haha. The changes your mentioned seems to be really good.

Thank you very much for answering. Keep up the good work.

I need to understand how I would change from socket.io to GraphQL Subscriptions entirely and if it would be possible (I accept suggestions). I want to unify this.

**Comment by DCtheTall** [comment]
@zefexdeveloper Yea feel free to fork this repository (or start your own repo) and take a shot at it. Admittedly I probably won't accept PRs for something like that but it'd be a fun exercise if you're interested!

**Comment by zefexdeveloper** [comment]
@DCtheTall I will for sure, thank you very much. By the way, one last question and I think others will be happy with this answer: how to run your example? I noticed that you assume that it's built already, what is the command to build that (how you do)?

**Comment by DCtheTall** [comment]
Building should be relatively straightforward (hopefully!) Assuming you have NPM and Node.js installed:

Run the following:
```bash
git clone https://github.com/DCtheTall/node-video-chat
cd node-video-chat
npm install
webpack --mode=production
```

The root `webpack.config.js` file should be used for config (which should be the case in the commands above) to build both the client side and server side code. Both servers use the same source code, and you can set which server you want to bring up using the `APP_NAME` environmental variable.

For example to run the GraphQL server:

```bash
APP_NAME=graphqlServer npm start
```
